---
title: "In Vitro Agarose IDA Analysis"
subtitle: "Analysis"
author: "Scott Saunders"
fontsize: 12pt
date: "08_21_19 "
output:
  html_document:
    self_contained: false
    toc: true
    code_folding: hide
  github_document:
    pandoc_args: --webtex
---

```{r setup, echo=T, message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
library(broom) 
library(modelr) 
library(viridis)
library(lubridate)
library(hms)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE, echo = TRUE, message=FALSE, warning=FALSE, fig.align="center")

source("../../tools/echem_processing_tools.R")
source("../../tools/plotting_tools.R")

theme_set(theme_1())
```


```{r}

swvGC_agarose <- read_csv("../../06_06_19_agarose_PYO_2/Processing/06_06_19_processed_swvGC_agarose.csv") %>% 
  group_by(reactor) %>% 
  mutate(min_time_gc = min(minutes_gc, na.rm = T), min_time_swv = min(minutes_swv, na.rm = T)) %>% 
  mutate(norm_time_gc = minutes_gc - min_time_gc, norm_time_swv = minutes_swv - min_time_swv) %>% 
  mutate(condition = 'agarose')

swvGC_ctDNA <- read_csv("../../08_13_19_agarose_ctDNA/processing/08_13_19_processed_swvGC_ctDNA.csv") %>% 
  mutate(minutes_gc = ifelse(minutes_gc < 1000, minutes_gc + 1440, minutes_gc)) %>% 
  mutate(minutes_swv = ifelse(minutes_swv < 1000, minutes_swv + 1440, minutes_swv)) %>% 
  group_by(reactor) %>% 
  mutate(min_time_gc = min(minutes_gc, na.rm = T), min_time_swv = min(minutes_swv, na.rm = T)) %>% 
  mutate(norm_time_gc = minutes_gc - min_time_gc, norm_time_swv = minutes_swv - min_time_swv) %>% 
  mutate(condition = 'ctDNA')

swvGC_glycerol <- read_csv("../processing/08_15_19_processed_swv_gc_max_glycerol.csv") %>% 
  filter(electrode_gc == 'i2') %>% 
  mutate(condition = 'glycerol')


swv_gc_df <- bind_rows(swvGC_agarose, swvGC_ctDNA, swvGC_glycerol) %>% 
  mutate(reactor_type = ifelse(reactor %in% c('soak', 'soak_2', 'soak1'), 'soak', 'transfer')) %>% 
  group_by(condition, electrode_swv) %>% 
  mutate(i0 = max(max_current_swv))
```


```{r}
ggplot(swv_gc_df, aes(x = norm_time_swv, y = max_current_swv, color = condition)) + geom_point()+ 
  facet_grid(rows = 'condition', scale = 'free_y') + xlim(0,150)
```

```{r}
ggplot(swv_gc_df %>% filter(rep > 2 & reactor_type == 'transfer' & electrode_swv == 'i1'), 
                            aes(x = norm_time_swv, y = max_current_swv, color = condition)) + geom_point()+ 
  facet_grid(rows = 'condition', scale = 'free_y') + xlim(0,150) + 
  geom_smooth(method='nls', formula=y~b*(x)^-0.5+a, method.args=list(start=c(b=1e-5,a=1e-5)) ,se=F) 
```

# Agarose

```{r}
ggplot(swv_gc_df %>% filter(condition == 'agarose' & reactor_type == 'transfer' & rep>0), 
       aes(x = norm_time_swv, y = max_current_swv)) + 
  geom_point() + 
  geom_smooth(method='nls', formula=y~b*(x)^-0.5+a, method.args=list(start=c(b=1e-5,a=1e-5)) ,se=F) +
  facet_wrap(~electrode_swv)

nls(formula = max_current_swv ~ (b* ((norm_time_swv)^-0.5)) + a, 
    data = swv_gc_df %>% filter(condition == 'agarose' & reactor_type == 'transfer' & rep>0 & electrode_swv == 'i1'),
    start = list(b=1e-5,a=1e-5))
```

```{r}

dm_from_a_OG <- function(estimate, i_0, dap, t_s=0.1){
  
  dm <- ( i_0^2 * dap * t_s ) / ( pi* estimate^2)
  
  dm
}
```

```{r}
nls_fits <- swv_gc_df %>% 
  filter(reactor_type =='transfer' & rep > 2) %>% 
  group_by(condition,reactor, electrode_swv) %>% 
  do(tidy(nls(.,formula = max_current_swv~(a*(norm_time_swv)^-0.5)+c,start=list(a=0.1,c=0)),conf.int = T) )

swv_gc_i0 <- swv_gc_df %>% 
  group_by(condition, electrode_swv) %>% 
  summarise(i0 = max(max_current_swv))

dphys_ests <- left_join(nls_fits, swv_gc_i0, by = c('condition','electrode_swv')) %>% 
  filter(term == 'a') %>% 
  mutate(d_phys = dm_from_a_OG(estimate = estimate, i_0 = i0, dap = 1e-5 , t_s = 0.047)) %>% 
  mutate(d_phys_low = dm_from_a_OG(estimate = conf.low, i_0 = i0, dap = 1e-5 , t_s = 0.047)) %>% 
  mutate(d_phys_high = dm_from_a_OG(estimate = conf.high, i_0 = i0, dap = 1e-5 , t_s = 0.047))

ggplot(dphys_ests, aes(x = condition, y = d_phys)) + geom_pointrange(aes(ymin = d_phys_low, ymax = d_phys_high))
```


```{r}
swv_gc_norm <- swv_gc_df %>% 
  group_by(condition, reactor, electrode_swv) %>% 
  mutate(bg_swv = max_current_swv - min(max_current_swv, na.rm = T), 
         bg_gc  = max_current_gc -  min(max_current_gc,  na.rm = T)) %>% 
  mutate(norm_swv = (bg_swv) / max(bg_swv, na.rm = T), 
         norm_gc  = (bg_gc) /  max(bg_gc,  na.rm = T))
  
ggplot(swv_gc_norm, aes(x = norm_time_gc, y = norm_gc, color = condition)) + geom_point()+ 
  facet_grid(rows = 'condition', scale = 'free_y') + xlim(0,150)

ggplot(swv_gc_norm, aes(x = norm_time_swv, y = norm_swv, color = condition)) + geom_point()+ 
  facet_grid(rows = 'condition', scale = 'free_y') + xlim(0,150)

ggplot(swv_gc_norm, aes(x = norm_time_swv, y = norm_swv, color = condition)) + 
  geom_hline(yintercept = 0.5)+
  geom_point()+ xlim(0,150) + facet_wrap(~reactor_type) 

ggplot(swv_gc_norm, aes(x = norm_time_gc, y = norm_gc, color = reactor)) + 
  geom_hline(yintercept = 0.5)+
  geom_point()+ xlim(0,150) + facet_wrap(~reactor_type)
```