---
title: "SI: EtBr-PHZ Competitive binding"
fontsize: 12pt
date: "03_14_19"
output:
  html_document:
    self_contained: false
    toc: true
    code_folding: hide
  github_document:
    pandoc_args: --webtex
---


```{r setup, echo=T, message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
library(viridis)
library(knitr)
library(kableExtra)
library(patchwork)
library(tidyr)
library(broom)

knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE, echo = TRUE, message=FALSE, warning=FALSE, fig.align="center")

source("../../../IDA/tools/echem_processing_tools.R")
source("../../../IDA/tools/plotting_tools.R")

theme_set(theme_1())
```

```{r}
etbr_data <- read_csv("../data/phz_etbr_competitive_binding.csv") %>% 
  gather(key = 'rep', value = 'fluor', -phz_conc, -phz_mol)

# Plot layout
etbr_plot <- ggplot(etbr_data %>% filter(phz_conc>0), aes(x = phz_conc, y = fluor)) + 
  geom_point(shape = 21) + 
  geom_smooth(color = 'black', linetype = 2) + 
  facet_wrap(~phz_mol, scales = 'free', ncol = 1) + 
  ylim(0,2000)

# Plot styling
etbr_plot_styled <- etbr_plot +
  labs(x = expression("Added phenazine"~(mu*M)), y = 'Ethidium Fluorescence') + 
  scale_x_log10(breaks = c(0.1, 1, 10, 100, 1000), labels = c("0.1", "1", "10", "100", "1000"))
  
etbr_plot_styled


etbr_data %>% group_by(phz_mol, phz_conc) %>% summarise(mean_fluor = mean(fluor)) 
```

```{r}
etbr_model_pyo <- nls(data = etbr_data %>% 
                        filter(phz_conc>0 & phz_mol=='PYO'), 
                      formula = fluor~max - (max*(phz_conc^hill)/((ic50^hill)+(phz_conc^hill))),
                      start=c(max=1500,hill=1,ic50=300))

etbr_model_pyo_CI <- tidy(etbr_model_pyo, conf.int = T) %>% filter(term=='ic50')




etbr_model_pcn <- nls(data = etbr_data %>% 
                        filter(phz_conc>0 & phz_mol=='PCN'), 
                      formula = fluor~max - (max*(phz_conc^hill)/((ic50^hill)+(phz_conc^hill))),
                      start=c(max=1500,hill=1,ic50=300))

confint(etbr_model_pcn)

summary(etbr_model_pyo)

etbr_model_pcn_CI <- tidy(etbr_model_pcn) %>% filter(term=='ic50') %>% 
  mutate(conf.low = estimate - (1.96 * std.error)) %>% 
  mutate(conf.high = estimate + (1.96 * std.error))

etbr_pred_pyo <- etbr_data %>% filter(phz_mol=='PYO') %>% add_predictions(etbr_model_pyo)

etbr_pred_pyo <- etbr_data %>% filter(phz_mol=='PYO') %>% 
  mutate(max = coef(etbr_model_pyo)[1], hill = coef(etbr_model_pyo)[2], ic50 = coef(etbr_model_pyo)[3]) %>% 
  mutate(ic50_high = etbr_model_pyo_CI$conf.high,ic50_low = etbr_model_pyo_CI$conf.low) %>% 
  mutate(pred = max - (max*(phz_conc^hill)/((ic50^hill)+(phz_conc^hill)))) %>% 
  mutate(pred_high = max - (max*(phz_conc^hill)/((ic50_high^hill)+(phz_conc^hill)))) %>% 
  mutate(pred_low = max - (max*(phz_conc^hill)/((ic50_low^hill)+(phz_conc^hill))))

etbr_pred_pcn <- etbr_data %>% filter(phz_mol=='PCN') %>% 
  mutate(max = coef(etbr_model_pcn)[1], hill = coef(etbr_model_pcn)[2], ic50 = coef(etbr_model_pcn)[3]) %>% 
  mutate(ic50_high = etbr_model_pcn_CI$conf.high,ic50_low = etbr_model_pcn_CI$conf.low) %>% 
  mutate(pred = max - (max*(phz_conc^hill)/((ic50^hill)+(phz_conc^hill)))) %>% 
  mutate(pred_high = max - (max*(phz_conc^hill)/((ic50_high^hill)+(phz_conc^hill)))) %>% 
  mutate(pred_low = max - (max*(phz_conc^hill)/((ic50_low^hill)+(phz_conc^hill))))

#etbr_pred_pcn <- etbr_data %>% filter(phz_mol=='PCN') %>% add_predictions(etbr_model_pcn)

ggplot(etbr_pred_pyo, aes(x = phz_conc, y = fluor)) + 
  geom_ribbon(aes(ymin = pred_low, ymax = pred_high), fill = 'light gray')+
  geom_line(aes(y = pred), linetype = 2) + 
  geom_point(shape = 21) + 
  scale_x_log10()

ggplot(etbr_pred_pcn, aes(x = phz_conc, y = fluor)) + 
  geom_ribbon(aes(ymin = pred_low, ymax = pred_high), fill = 'light gray')+
  geom_line(aes(y = pred), linetype = 2) + 
  geom_point(shape = 21) + 
  scale_x_log10()

ggplot(etbr_data %>% filter(phz_conc>0 & phz_mol=='PYO') %>% mutate(norm_fluor = -fluor + 1500), 
       aes(x = phz_conc, y = norm_fluor)) + 
  geom_point(shape = 21) + 
  scale_x_log10()

```

```{r}
etbr_preds = bind_rows(etbr_pred_pyo, etbr_pred_pcn, etbr_data %>% filter(phz_mol=='PCA'))

etbr_plot <- ggplot(etbr_preds %>% filter(phz_conc>=1), aes(x = phz_conc, y = fluor)) + 
  geom_ribbon(aes(ymin = pred_low, ymax = pred_high), fill = 'light gray')+
  geom_line(aes(y = pred), linetype = 2) + 
  geom_point(shape = 21) + 
  facet_wrap(~phz_mol, scales = 'free', ncol = 1)

etbr_plot_styled <- etbr_plot +
  labs(x = expression("Added phenazine"~(mu*M)), y = 'Ethidium Fluorescence') + 
  scale_x_log10(breaks = c(0.1, 1, 10, 100, 1000), labels = c("0.1", "1", "10", "100", "1000"))
  
etbr_plot_styled
```

```{r}

etbr_kd = 1 #uM

etbr_conc = 5 #uM 


```

$$K_i = \frac{IC_{50}}{1+\frac{[EtBr]}{K_d}}$$
$$K_i = \frac{IC_{50}}{6}$$

For PCN Ki = 612 / 6 = 102uM
PCN low Ki = 450 / 6 = 75
PCN high Ki = 774 / 6 = 129

For PYO Ki = 275 / 6 = 45.8 uM
PYO low Ki = 214 / 6 = 35.8
PYO high Ki = 364 / 6 = 60.7

```{r}
save_plot("../figures/03_14_19_fig_supp_etbr.pdf", etbr_plot_styled ,base_width = 4, base_height = 6 )

```

```{r}
mst_data <- read_csv("../data/MST_data_phz_DNA.csv") %>% 
  mutate(norm_resp = Response - 640)

ggplot(mst_data, aes(x = Dose, y = norm_resp)) + 
  geom_point() + 
  geom_smooth(method='nls',
              formula=y~max*(x^hill)/((Kd^hill)+(x^hill)),
              method.args=list(start=c(max=400,hill=1,Kd=100)),
              se=F, color = 'black', linetype = 'dashed', size = 0.5) +
  facet_wrap(~phz_mol, scales = 'free', ncol=1)

model_pyo <- nls(data = mst_data %>% filter(phz_mol=='PYO') ,formula = norm_resp~max*(Dose^hill)/((Kd^hill)+(Dose^hill)),start=c(max=400,hill=1,Kd=100) )
  
model_pcn <- nls(data = mst_data %>% filter(phz_mol=='PCN') ,formula = norm_resp~max*(Dose^hill)/((Kd^hill)+(Dose^hill)),start=c(max=400,hill=1,Kd=100) )

confint_pyo <- tidy(model_pyo, conf.int = T) %>% filter(term=='Kd')

summary(model_pcn)

confint_pcn <- tidy(model_pcn) %>% filter(term=='Kd') %>% 
  mutate(conf.low = estimate - (1.96*std.error), conf.high = estimate + (1.96*std.error))
  
pred_pyo <- mst_data %>% filter(phz_mol=='PYO') %>% 
  mutate(max = coef(model_pyo)[1], hill = coef(model_pyo)[2], kd = coef(model_pyo)[3]) %>% 
  mutate(kd_low = confint_pyo$conf.low,kd_high = confint_pyo$conf.high ) %>% 
  mutate(pred = max*(Dose^hill)/((kd^hill)+(Dose^hill))) %>% 
  mutate(pred_low = max*(Dose^hill)/((kd_low^hill)+(Dose^hill))) %>% 
  mutate(pred_high = max*(Dose^hill)/((kd_high^hill)+(Dose^hill))) 

pred_pcn <- mst_data %>% filter(phz_mol=='PCN') %>% 
  mutate(max = coef(model_pcn)[1], hill = coef(model_pcn)[2], kd = coef(model_pcn)[3]) %>% 
  mutate(kd_low = confint_pcn$conf.low,kd_high = confint_pcn$conf.high ) %>% 
  mutate(pred = max*(Dose^hill)/((kd^hill)+(Dose^hill))) %>% 
  mutate(pred_low = max*(Dose^hill)/((kd_low^hill)+(Dose^hill))) %>% 
  mutate(pred_high = max*(Dose^hill)/((kd_high^hill)+(Dose^hill))) 

preds <- bind_rows(pred_pyo,pred_pcn,mst_data %>% filter(phz_mol=='PCA'))

# Plot layout
mst_plot <- ggplot(preds, aes(x = Dose, y = norm_resp)) + 
  geom_ribbon(aes(ymin = pred_low, ymax = pred_high), fill = 'light gray')+
  geom_line(aes(y = pred), linetype = 2) +
  geom_point(shape = 21) + 
  facet_wrap(~phz_mol, scales = 'free',ncol=1)+ 
  scale_x_log10()

# Plot styling
mst_plot_styled <- mst_plot +
  labs(x = expression("Added phenazine"~(mu*M)), y = "Thermophoresis response")

mst_plot_styled
```

Kd for PCN = 133.6 uM
Kd for PYO = 536.4 uM (but doesn't saturate)

```{r}
binding_plots <- plot_grid(etbr_plot_styled,mst_plot_styled, ncol=2, scale = 0.9, align = 'hv', axis = 'tblr', labels = c("A","B"))

save_plot("../figures/03_21_19_fig_supp_binding.pdf", binding_plots ,base_width = 6, base_height = 5 )

```

