---
title: "SI Fig: Psoralen"
fontsize: 12pt
date: "03_22_19"
output:
  html_document:
    self_contained: false
    toc: true
    code_folding: hide
  github_document:
    pandoc_args: --webtex
---


```{r setup, echo=T, message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
library(broom) 
library(modelr) 
library(viridis)
library(lubridate)
library(hms)
library(knitr)
library(kableExtra)
library(patchwork)
library(VGAM)
library(nls.multstart)


knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), echo = TRUE, message=FALSE, warning=FALSE, fig.align="center")

source("../../../IDA/tools/echem_processing_tools.R")
source("../../../IDA/tools/plotting_tools.R")

theme_set(theme_1())
```

# Dap / Dphys comparison

```{r}
biofilm_dap <- read_csv("../../02_05_19_draft_2/data/01_28_19_swv_gc_dap_estimates_aggregate_updated.csv") %>% 
  filter((treatment=='control' & exp_id!='1' & echem_from_swv=='SWV') | (treatment=='psoralen' & exp_id =='3' & run==1))

biofilm_signals <- read_csv('../../02_05_19_draft_2/data/01_28_19_aggregate_SWV_GC_signals.csv') %>%
  filter((treatment=='control' & exp_id!='1' & echem_from_swv=='SWV') | 
           (treatment=='psoralen' & exp_id =='3' & run==1)) %>% 
  filter(electrode_from_swv=='i1')
  

biofilm_signals_norm <- biofilm_signals %>%  
  group_by(treatment,exp_id,reactor,run) %>% 
  mutate(min_time = min(minutes_from_swv)) %>% 
  mutate(norm_time = minutes_from_swv - min_time + 0.6)

biofilm_soak_i0 <- biofilm_signals_norm %>% 
  ungroup() %>% 
  filter(reactor=='soak' & rep==0) %>% 
  mutate(i0_high = signal_from_swv) %>% 
  select(treatment,run,exp_id, i0_high) 

biofilm_transfer_i0 <- biofilm_signals_norm %>% 
  ungroup() %>% 
  filter(reactor=='transfer' & rep==0) %>% 
  mutate(i0_low = signal_from_swv) %>% 
  select(treatment,run,exp_id, i0_low) 

biofilm_i0 <- left_join(biofilm_soak_i0, biofilm_transfer_i0, by = c('treatment','exp_id','run'))

biofilm_signals_i0 <- left_join(biofilm_signals_norm %>% 
                                   ungroup() %>%  
                                   filter(reactor=='transfer') %>%
                                   mutate(signal = signal_from_swv) %>% 
                                   select(treatment,exp_id, run, rep, signal, norm_time), biofilm_i0, 
                                 by = c('treatment','exp_id', 'run')) 

biofilm_signals_dap <- left_join(biofilm_signals_i0, biofilm_dap, by = c('treatment','exp_id', 'run')) %>% 
  mutate(IDA = 'biofilm', run = as.character(run)) 

ggplot(biofilm_signals_dap, aes(x = norm_time, y = signal)) + 
  geom_point() +
  geom_line(aes(y = i0_high), linetype = 2)+
  geom_line(aes(y = i0_low), linetype = 2, color = 'red')+
  facet_wrap(vars(treatment,exp_id,run), scales = 'free')
```

psoralen curve decays relatively fast, which isn't abnormal, but we'll see what it does to the estimate.

```{r}

dm_from_a_OG <- function(estimate, i_0, dap, t_s=0.1){
  
  dm <- ( i_0^2 * dap * t_s ) / (pi* estimate^2)
  
  dm
}

ggplot(biofilm_signals_dap, aes(x = norm_time, y = signal)) + 
  geom_smooth(method = "nls", 
    formula = y ~ b * (x)^-0.5 + a, method.args = list(start = c(b = 0.1, 
        a = 1e-07)), se = F)+
  geom_point(shape = 21)+
  facet_wrap(vars(treatment,exp_id, run), scales = 'free', ncol = 3)
```

```{r}
decay_data_nls <- biofilm_signals_dap %>%
  group_by(treatment, exp_id, run) %>% 
  do(
    tidy(
      nls(data = ., formula =  signal ~ b * (norm_time)^-0.5 + a, start = c(b = 0.1, 
        a = 1e-07) ),
      conf.int = T
    )
  )

nls_estimate <- decay_data_nls %>%
  select(-std.error, - statistic, - p.value, -conf.high, - conf.low) %>% 
  spread(key = term, value = estimate) %>% 
  rename(a_mean = a, b_mean = b)
  
nls_low <- decay_data_nls %>%
  select(-std.error, - statistic, - p.value, -conf.high, - estimate) %>% 
  spread(key = term, value = conf.low) %>% 
  rename(a_low = a, b_low = b)

nls_high <- decay_data_nls %>%
  select(-std.error, - statistic, - p.value, -conf.low, - estimate) %>% 
  spread(key = term, value = conf.high) %>% 
  rename(a_high = a, b_high = b)

nls_high_low <- left_join(nls_low, nls_high, by = c('treatment', 'exp_id', 'run'))

nls_terms <- left_join(nls_estimate, nls_high_low, by = c('treatment', 'exp_id', 'run') )

decays_combined_nls <- left_join(biofilm_signals_dap, nls_terms, by = c('treatment', 'exp_id', 'run')) %>% 
  mutate(dphys = dm_from_a_OG(estimate = b_mean, i_0=i0_high, dap = dap, t_s = 0.02)) %>% 
  mutate(dphys_low = dm_from_a_OG(estimate = b_low, i_0=i0_high, dap = dap, t_s = 0.02)) %>% 
  mutate(dphys_high = dm_from_a_OG(estimate = b_high, i_0=i0_high, dap = dap, t_s = 0.02)) 

dphys_estimates <- decays_combined_nls %>% 
  group_by(treatment, exp_id, run) %>% 
  summarise(dphys = mean(dphys), low = mean(dphys_low), high = mean(dphys_high)) %>% 
  gather(key = dcat, value = estimate, dphys)

dap_estimates <- decays_combined_nls %>% 
  group_by(treatment, exp_id, run) %>% 
  summarise(dap = mean(dap), low = mean(dap_low), high = mean(dap_high)) %>% 
  gather(key = dcat, value = estimate, dap)

d_estimates <- bind_rows(dphys_estimates, dap_estimates)

d_estimates$dcat = factor(d_estimates$dcat, labels= c('D[ap]','D[phys]'))

levels(d_estimates$dcat)

plot_psoralen <- ggplot(d_estimates, aes(x = treatment, y = estimate)) + 
  geom_pointrange(aes(ymin = low, ymax = high), position = position_jitter(width = 0.1, height = 0), size = 0.25) +
  facet_wrap(~dcat, scales = 'free',labeller = label_parsed) + scale_y_log10(limits = c(1e-8, 2e-5))

plot_psoralen_styled <- plot_psoralen+
  labs(x='Treatment',y=expression("Estimate ("~cm^2 / sec~")"))

plot_psoralen_styled
```

Dphys estimate just uses high limit of i0 with t_s = 20ms

# Psoralen Growth Curve

```{r}
pr_data <- read_csv("../data/01_21_19_psoralen_toxicity_growth_curve.csv") %>% 
    gather(key = well, value = abs, -time) %>% mutate(time = as.numeric(time)/60)

pr_metadata <- read_csv("../data/01_21_19_psoralen_platereader_metadata.csv")

df_pr <- left_join(pr_data, pr_metadata, by = "well")
```

```{r}
plot_psorGrowth <- ggplot(df_pr %>% filter(strain=='dPHZstar' & psoralen!='None'), aes(x = as.numeric(time)/60, y = abs, color = factor(psoralen))) + 
    geom_smooth(se=F) + scale_color_viridis(discrete = T)

plot_psorGrowth_styled <- plot_psorGrowth+
  theme(legend.position = c(0.2,0.8)) +
  labs(x = 'Hours', y = "Absorbance - 500nm", color = expression(TMP~(mu*M)))

plot_psorGrowth_styled
```

# Psoralen crosslink formation

```{r}
df <- read_csv("../data/10uM_TMP_8MOP_DNA_UVA_Timecourse.csv", 
    skip = 13) %>% gather(key = label, value = intensity, -Wavelength)

labels <- read_csv(("../data/psoralen_platereader_label_metadata.csv"))

pr_data <- left_join(df, labels, by = "label")
```
asdfasdf

```{r}

plot_crosslink <- ggplot(pr_data %>% filter(DNA == "plus" & molecule == "tmp"), 
    aes(x = Wavelength, y = intensity, group = factor(light_time), color = factor(light_time))) + 
  geom_point() + geom_line() + 
  xlim(340, 540) + ylim(0, 40000) + scale_color_viridis(discrete = T)

plot_crosslink_styled <- plot_crosslink + 
  labs(x = 'Emission wavelength (nm)',y = 'Fluorescence intensity (A.U.)', color = '365nm exposure\n(min)') + 
  theme(legend.position = c(0.9, 0.7))

plot_crosslink_styled
```

# Grid figure

```{r}
psoralen_grid <- plot_grid(plot_crosslink_styled, plot_crosslink_styled, plot_psorGrowth_styled, plot_psoralen_styled, ncol = 2, align = 'hv', axis = 'tblr', labels = c("A", "B", "C", "D"), scale = 0.9)

psoralen_grid

save_plot("../figures/03_22_19_fig_supp_Psoralen.pdf", psoralen_grid ,base_width = 7, base_height = 6 )

```
