---
title: "Propidium and Ethidium with Colony Biofilms"
subtitle: "LC-MS Quantifications from exp 07-23-19"
author: "Scott Saunders"
fontsize: 12pt
date: '09-23-2019'
output:
  html_document:
    theme: cosmo
    code_folding: hide
    self_contained: no
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
  github_document:
    pandoc_args: --webtex
---


```{r setup, echo=T, message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
library(viridis)
library(knitr)
library(kableExtra)



knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE, echo = TRUE, message=FALSE, warning=FALSE, fig.align="center")

source("../../../../IDA/tools/plotting_tools.R")

theme_set(theme_1())
```

# Intro

adsf

# Methods

## Samples

Images are available in [my google drive](https://drive.google.com/open?id=14sU_BI-pYdzNY28JaxuKqH0OJQ52PsHQ). 

### WT

WT colonies for TOTO measurement

* WT Toto - 6 biofilm, 6 agar

WT controls for EtBr

* WT H2O - 3 cells, 3 agar

WT controls for PI

* WT dmso - 3 cells, 3 agar

WT exp w/ EtBr

* WT EtBr 10uM  - 3 cells, 3 agar
* WT EtBr 100uM  - 3 cells, 3 agar
* WT EtBr 500uM  - 3 cells, 3 agar

WT exp w/ PI

* WT PI 10uM  - 3 cells, 3 agar
* WT PI 100uM  - 3 cells, 3 agar
* WT PI 200uM  - 3 cells, 3 agar

 = 60 samples
 
------

### ∆phz*

∆phz* + PYO + EtBr 

* ∆phz* + 50uM PYO + 10uM EtBr - 2 cells, 2 agar
* ∆phz* + 50uM PYO + 100uM EtBr - 2 cells, 2 agar
* ∆phz* + 50uM PYO + 500uM EtBr - 2 cells, 2 agar 

∆phz* + PCN + EtBr 

* ∆phz* + 50uM PCN + 10uM EtBr - 2 cells, 2 agar
* ∆phz* + 50uM PCN + 100uM EtBr - 2 cells, 2 agar
* ∆phz* + 50uM PCN + 500uM EtBr - 2 cells, 2 agar 

∆phz* + PYO + PI 

* ∆phz* + 50uM PYO + 10uM PI - 2 cells, 2 agar
* ∆phz* + 50uM PYO + 100uM PI - 2 cells, 2 agar
* ∆phz* + 50uM PYO + 200uM PI - 2 cells, 2 agar 

∆phz* + PCN + PI 

* ∆phz* + 50uM PCN + 10uM PI - 2 cells, 2 agar
* ∆phz* + 50uM PCN + 100uM PI - 2 cells, 2 agar
* ∆phz* + 50uM PCN + 200uM PI - 2 cells, 2 agar 

 = 48 samples
 
 --------
 
  = 108 samples total
  
First run is WT H2O and WT WT EtBr Samples

## Sample Prep 

Samples were extracted as normal. Colonies were resuspended in **800uL of PBS 137(?? - check this)** and agar was extracted for ~3 hours in 3mL of PBS 137. Note that some of the colonies did not break up entirely, particularly in the PI and EtBr treated colonies. However, they were all incubated in the liquid for the same amount of time, so I would expect that the phenazines were extracted reasonably well. [Photos in the google drive](https://drive.google.com/open?id=19L6UKPxe9BR9Wcf2IP9riKZ4O-mz0Dz_) show some of the prep and differences in colony pellets etc. 

  
Frozen samples were thawed to room temp, then filtered with 0.2um spinX columns. 500uL of samples were then transferred into sample vials containing 500uL of PBS 137 and therefore samples were run at a **0.5 x dilution.**  
  
Samples were run using the standard Phenazine_basic_MS method on the waters LC-MS.
  
# Results

## First pass

Here are the results from the first quantification. Let's read in the data:
```{r}
df_wt <- read_csv("../data/2019_07_23_colony_HPLC_wt_data.csv")

df_dphz <- read_csv("../data/2019_07_23_colony_HPLC_dPHZ_data.csv")
```

Here's the raw WT data:

```{r}

colorblind_palette <- c("#E69F00", "#56B4E9", "#000000","#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


ggplot(df_wt %>% filter(condition != 'blank'), aes(x = condition, y = Amount, color = condition_conc)) + geom_point() + facet_wrap(material~measured_phz, scales = 'free') + scale_color_manual(values = colorblind_palette, na.value='gray')
```

The only thing that caught my eye here is the PYO measured in the 100uM etbr cells. You can see one value is at zero, while the other is at 4. That seems like a mistake to me - may need to requantify.

Here's the raw ∆phz* data:

```{r}
ggplot(df_dphz %>% filter(condition != 'blank'), aes(x = measured_phz, y = Amount, color = condition_conc, shape = condition)) + 
  geom_point() + 
  facet_wrap(~added_phz, scales = 'free') + 
  scale_color_manual(values = colorblind_palette, na.value='gray')
```
This looks pretty good to me. Let's go back and look at the WT sample that seemed to be a false negative.

## Second pass

After looking at the run the PYO peaks are closer to 6.1 min retention time instead of 6.0, so the integration algorithm missed that one peak. I figured it might have missed others, but done it in a more consistent way across samples, so I just requantified everything looking for the PYO peak near 6.1min. Here's the second quantification of the data:

```{r}
df_wt_2 <- read_csv("../data/2019_07_23_colony_HPLC_wt_data_2.csv")

df_wt_2 <- df_wt_2 %>%
  mutate(condition_conc = fct_relevel(condition_conc, c('0uM','10uM','100uM','200uM','500uM'))) %>% 
  mutate(condition = fct_relevel(condition, c('h2o','etbr','dmso','pi')))


df_dphz_2 <- read_csv("../data/2019_07_23_colony_HPLC_dPHZ_data_2.csv")

df_dphz_2 <- df_dphz_2 %>% 
  mutate(condition_conc = fct_relevel(condition_conc, c('0uM','10uM','100uM','200uM','500uM'))) %>% 
    mutate(condition = fct_relevel(condition, c('PBS','etbr','dmso','pi')))

```

```{r}

ggplot(df_wt_2 %>% filter(condition != 'blank'), aes(x = condition, y = Amount, color = condition_conc)) + geom_point() + facet_wrap(material~measured_phz, scales = 'free') + ylim(0, NA)
```


```{r}

ggplot(df_dphz_2 %>% filter(condition != 'blank'), aes(x = condition, y = Amount, color = condition_conc)) + 
  geom_point() + 
  facet_wrap(added_phz~measured_phz, scales = 'free') + ylim(0, NA)

```
Focus on the PCN - PCN and PYO - PYO panels, since those are the only values that are real. The other panels just show that indeed we don't detect significant amounts of other phenazines when they are not added to ∆phz*.

Ok, looks good, so now I'll go ahead and convert the values into biofilm and agar concentrations and retention ratios.

```{r}
df_wt_conc <- df_wt_2 %>% 
  mutate(measured_phz_conc = case_when(
    material == 'cells' ~ (Amount * 2) * (800 / 60),
    material == 'agar' ~ (Amount * 2) * (8 / 5)
  )) %>% 
  group_by(measured_phz, strain, condition, condition_conc, material) %>% 
  mutate(mean_phz_conc = mean(measured_phz_conc))

df_wt_retRatio <- left_join(df_wt_conc %>% filter(material == 'cells'), df_wt_conc %>% filter(material == 'agar'), 
                            by = c('measured_phz', 'strain','condition','condition_conc','rep'), 
                            suffix = c('_cells','_agar')) %>% 
  mutate(ret_ratio = measured_phz_conc_cells / measured_phz_conc_agar) %>% 
  group_by(measured_phz, strain, condition, condition_conc) %>% 
  mutate(mean_ret_ratio = mean(ret_ratio))
  

df_dphz_conc <- df_dphz_2 %>% 
  filter(added_phz == measured_phz) %>% 
  mutate(measured_phz_conc = case_when(
    material == 'cells' ~ (Amount * 2) * (800 / 60),
    material == 'agar' ~ (Amount * 2) * (8 / 5)
  )) %>% 
  group_by(measured_phz, strain, condition, condition_conc) %>% 
  mutate(mean_phz_conc = mean(measured_phz_conc))
  
  
```

## EtBr

### WT

```{r}

ggplot(df_wt_conc %>% filter(condition %in% c('etbr','h2o')), aes(x = condition_conc, y = measured_phz_conc)) +
  geom_col(data = df_wt_conc %>% filter(condition %in% c('etbr','h2o')) %>% filter(rep == 1),
           aes(x = condition_conc, y = mean_phz_conc), fill = 'light gray') + 
  geom_point(shape = 21)  + facet_wrap(material~measured_phz, scales = 'free') + ylim(0, NA)

```

```{r}

plot_wt_etbr <- ggplot(df_wt_retRatio %>% filter(condition %in% c('etbr','h2o')), aes(x = condition_conc, y = ret_ratio)) +
  geom_col(data = df_wt_retRatio %>% filter(condition %in% c('etbr','h2o')) %>% filter(rep == 1),
           aes(x = condition_conc, y = mean_ret_ratio), fill = 'light gray') + 
  geom_point(shape = 21)  + facet_wrap(~measured_phz, scales = 'free') + ylim(0, NA) + 
  labs(x = expression('EtBr added to agar'~(mu*M)), y = 'Retention ratio ( [biofilm] / [agar] )', title = 'WT phenazine - competition with EtBr') + 
  scale_x_discrete(labels = c(0, 10, 100, 500))

#saveRDS(plot_wt_etbr, "../../../../Figures/2019_09_27_group_meeting/plot_wt_etbr")

plot_wt_etbr
```

### ∆phz*

```{r}


plot_dphz_etbr <- ggplot(df_dphz_conc %>% filter(condition %in% c('etbr','PBS')), 
       aes(x = condition_conc, y = measured_phz_conc)) + 
  geom_col(data = df_dphz_conc %>% filter(condition %in% c('etbr','PBS') & rep ==1), 
           aes(x = condition_conc, y  = mean_phz_conc), fill = 'light gray') +
  geom_point(shape = 21)  + facet_wrap(~measured_phz, scales = 'free') + ylim(0, NA) + 
  labs(x = expression('EtBr added to agar'~(mu*M)), y = expression('Biofilm phz concentration'~(mu*M)), title = 'dPHZ* + 50uM PCN or PYO vs. EtBr')+
  scale_x_discrete(labels = c(0, 10, 100, 500))


#saveRDS(plot_dphz_etbr, "../../../../Figures/2019_09_27_group_meeting/plot_dphz_etbr")

plot_dphz_etbr
```

## PI

### WT

```{r}

ggplot(df_wt_conc %>% filter(condition %in% c('pi','h2o','dmso')), 
       aes(x = condition_conc, y = measured_phz_conc,color = condition)) +
  geom_col(data = df_wt_conc %>% filter(condition %in% c('pi','h2o','dmso') & rep ==1),
           aes(x = condition_conc, y = mean_phz_conc), fill = 'light gray', position = 'dodge') + 
  geom_point(shape = 21, position = position_dodge(width = 1))  + facet_wrap(material~measured_phz, scales = 'free') + ylim(0, NA)

```

```{r}

plot_wt_pi <- ggplot(df_wt_retRatio %>% filter(condition %in% c('pi','h2o','dmso')), 
       aes(x = condition_conc, y = ret_ratio, color = condition)) +
  geom_col(data = . %>% filter(rep == 1),
           aes(y = mean_ret_ratio), fill = 'light gray', position = 'dodge') + 
  geom_point(shape = 21, position = position_dodge(width=1))  + 
  facet_wrap(~measured_phz, scales = 'free') + ylim(0, NA)+
  labs(x = expression('PI added to agar'~(mu*M)), y = 'Retention ratio ( [biofilm] / [agar] )', title = 'WT phenazine - competition with PI') + 
  scale_x_discrete(labels = c(0, 10, 100, 200)) + 
  theme( legend.position='top', legend.title = element_text(size=12))

#saveRDS(plot_wt_pi, "../../../../Figures/2019_09_27_group_meeting/plot_wt_pi")

plot_wt_pi

```

### ∆phz*

```{r}
ggplot(df_dphz_2 %>% filter(condition %in% c('pi','PBS','dmso') & measured_phz != 'PCA'), aes(x = condition_conc, y = Amount, shape = added_phz, color = condition)) + 
  geom_point()  + 
  facet_wrap(material~measured_phz, scales = 'free') + 
  ylim(0, NA) + 
  scale_shape_discrete(solid = F)

plot_dphz_pi <- ggplot(df_dphz_conc %>% filter(condition %in% c('pi','PBS','dmso')), 
       aes(x = condition_conc, y = measured_phz_conc, color = condition)) + 
  geom_col(data = . %>% filter(rep ==1), 
           aes(y  = mean_phz_conc), fill = 'light gray', position = 'dodge') +
  geom_jitter(shape = 21, position = position_jitterdodge(dodge.width = 1))  + 
  facet_wrap(~measured_phz, scales = 'free') + ylim(0, NA)+
  labs(x = expression('PI added to agar'~(mu*M)), y = expression('Biofilm phz concentration'~(mu*M)), title = 'dPHZ* + 50uM PCN or PYO vs. PI') + 
  scale_x_discrete(labels = c(0, 10, 100, 200)) +
  theme( legend.position='top', legend.title = element_text(size=12))

#saveRDS(plot_dphz_pi, "../../../../Figures/2019_09_27_group_meeting/plot_dphz_pi")

plot_dphz_pi
```

# Discussion

One issue here is colony size. We should look back at this. Another issue seems to be that DMSO strongly affects both WT and dPHZ retention.

------
  
```{r}
sessionInfo()  
```
