---
title: "Biofilm Echem Analysis: Past, Present, and Future"
fontsize: 12pt
date: "01_03_19"
output:
  html_document:
    self_contained: false
    code_folding: hide
  github_document:
    pandoc_args: --webtex
---

Each notebook entry below will discuss the approach, the problems with that approach and potential solutions. This leads into the next version of the analysis. 

## Measuring $D_{ap}$

We set out to measure the $D_{ap}$ for PYO in the IDA grown biofilm based on a sensitive generator/collector (gc) measurement. 

### [V1: Soak titration $I_{gc}$ vs. [PYO]](https://scott-saunders.github.io/labwork/IDA/01_03_19_Update/Dap_V1.html) 

* **Approach:** Originally, we were just soaking a biofilm in a concentration of PYO and looking at how current increased. Recall, the main goal was to see if the relationship was linear or nonlinear. 

* **Problem:** We realized that most of the signal is coming from the solution phase PYO, not necessarily PYO associated with the biofilm.

* **Solution:** Try to transfer the biofilm to fresh media.

### [V2: Transfer equilibrium titration $I_{gc}$ vs. $I_{swv}$](https://scott-saunders.github.io/labwork/IDA/01_03_19_Update/Dap_V2.html) 

* **Approach:** We decided to transfer the biofilm to a fresh reactor after soaking, so that we would be measuring biofilm associated PYO. In the course of monitoring the PYO equilibrate out of the biofilm into the fresh media, we realized it might be possible to measure $D_m$. We no longer knew the concentration of PYO at the electrode, so we then adopted the SWV vs. GC measurement. Typically, we waited for the PYO to equilibrate between the biofilm and the fresh solution. 

* **Problem:** At "equilibrium," , the solution concentration of PYO was no longer negligible, presenting the same problem as in V1 above. This was seen by measuring the solution with a blank IDA after the biofilm IDA measurements. 

* **Solution:** Measure in the transfer reactor before equilbrium when we can be confident PYO is associated with the biofilm. Also, try to carry over less PYO into the transfer reactor and explicitly measure the background solution PYO with a blank IDA.

### [V3: Transfer non-equilibrium titration $I_{gc}$ vs. $I_{swv}$](https://scott-saunders.github.io/labwork/IDA/01_03_19_Update/Dap_V3.html) 

* **Approach:** Measure while PYO is equilibrating with the transfer solution, by taking a 1 segment GC scan (~3min) immediately followed by a ~2sec SWV scan. By measuring before equilibrium, we can be confident that we are measuring biofilm associated PYO, and not solution phase PYO. Also, because we can get multiple datapoints following soak in one PYO concentration, we can gather more datapoints in less time. 

* **Potential problem:** Multiple GC measurements during equilibration may effectively drive PYO out of the biofilm, disrupting the measurement of $D_m$. 

* **Potential solution:** Make separate measurement of $D_m$ by monitoring a separate equilibration with only intermittent SWV (as in V2).

## Measuring $D_m$

From monitoring PYO equilibration for $D_{ap}$ V2, it seemed possible to measure the physical diffusion coefficient of PYO $D_m$ from the consecutive SWVs taken to monitor the equilibration.

### V1: SWV decays - $P_1$ = $I_0$ 

* **Approach:** Monitor equilibration with successive SWV scans (slow - 40sec each). Estimate the initial current, $I_0$, with the first datapoint, $P_1$. 

* **Problem:** The first datapoint, $P_1$, is not at all a reasonable estimate of initial current, $I_0$. This throws off the estimate of $D_m$ by orders of magnitude. This became clear by analyzing a blank IDA where the soak SWV is known to be $I_0$. [blank IDA analysis notebook](https://scott-saunders.github.io/labwork/IDA/11_28_18_blank_IDA/Analysis/11_28_18_blank_IDA_Analysis.html)

* **Solution:** We can accept that we may never know the true $I_0$, but we should be able to bound our estimates by assuming that $I_0$ lies between the SWV signal from the soak (preceding transfer) and $P_1$.


### [SWV decay simulation](https://scott-saunders.github.io/labwork/IDA/12_10_18/Analysis/generating_and_decoding_diffusion.html)

Simulating these SWV decay curves from our diffusion equation further convinces me that we cannot estimate $I_0$ from any type of analysis of the transfer SWVs.

### V2: SWV decays, constrain $I_0$

* **Approach:** From the solution described in V1, attempt to constrain an estimate of $I_0$ between the soak SWV and first datapoint. To do this well, we should use fast SWVs (2sec duration) and try to start the scans as quickly as possible following transfer. Also, it is important to time how long it takes between first the moment the biofilm touches the transfer reactor till the first SWV is actually acquired. I think there will be advantages and disadvantages to washing the biofilm before transfer.

This experiment has not been attempted yet. 
