---
title: "Figure 4"
fontsize: 12pt
date: '01_30_19 '
output:
  powerpoint_presentation:
  html_document:
    code_folding: hide
    self_contained: no
    toc: yes
  github_document:
    pandoc_args: --webtex
  
subtitle: ''
---


```{r setup, echo=T, message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
library(broom) 
library(modelr) 
library(viridis)
library(lubridate)
library(hms)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE, echo = T, message=FALSE, warning=FALSE, fig.align="center", dpi = 300 )

#source("../../tools/echem_processing_tools.R")
source("../IDA/tools/plotting_tools.R")

theme_set(theme_1())
```



### D_ap (Standard Scale)

* $D_{ap}$ of PYO in the biofilm can be estimated. 
* $D_{ap}$ of biofilm PYO is lower than PYO in solution.



```{r }
df <- read_csv("../IDA/01_28_19_psoralen_nonequil_aggregate/Analysis/01_28_19_swv_gc_dap_estimates_aggregate.csv")

ggplot(df %>% filter(treatment!='psoralen' & echem_from_swv!='SWVslow'), 
       aes(x = treatment, y = dap, color = exp_id)) +
  geom_pointrange(aes(ymin = dap_low, ymax = dap_high),position = position_jitter(height = 0, width = 0.2))+
  scale_color_viridis(discrete = T)+
  labs(y=expression(D[ap] (cm^2 / sec)),color='Experiment #') 

```



### D_ap (Log Scale)


```{r}

d_ap <- ggplot(df %>% filter(treatment!='psoralen' & echem_from_swv!='SWVslow'), 
       aes(x = treatment, y = dap, color = exp_id)) +
  geom_pointrange(aes(ymin = dap_low, ymax = dap_high),position = position_jitter(height = 0, width = 0.2))+
  scale_color_viridis(discrete = T)+
  labs(y=expression(D[ap] (cm^2 / sec)),color='Experiment #') +
  scale_y_log10(limits = c(1e-8, 2.5e-5))

d_ap
```

```{r}
dm <- read_csv("../IDA/01_17_19_psoralen_nonequil_2/Analysis/01_17_19_dm_estimates.csv") %>% 
  rowwise() %>% 
  mutate(mean = mean(c(dm_soak,dm_transfer)))

d_m <- ggplot(dm %>% filter(model=='no_flux' & electrode=='i1'), 
       aes(x = biofilm,y=mean, color = run)) +
  geom_pointrange(aes(ymin = dm_transfer, ymax = dm_soak),position = position_jitter(height = 0, width = 0.2))+
  scale_color_viridis(discrete = T)+
  labs(y=expression(D[m] (cm^2 / sec)),color='Experiment #') +
  scale_y_log10(limits = c(1e-8, 2.5e-5))

d_m
```


```{r}
plot_grid(d_ap,d_m, align = "hv", axis = 'tblr')
```