---
title: 'Version 0.2'
output: 
  flexdashboard::flex_dashboard:
    source_code: https://github.com/scott-saunders/labwork/blob/master/Growth_curve_fitting/growth_curve_shiny.Rmd
fontsize: 12pt
runtime: shiny
---

```{r setup}
library(tidyverse)
library(cowplot)
library(viridis)
library(knitr)
library(kableExtra)
library(modelr)
library(broom)
library(ggforce)
```

# Column {.sidebar}

## Gompertz Curve Fitting

-----

Use this app to fit growth curves, whether it is one experiment or hundreds (e.g. from a plate reader).

Start by uploading a .csv file of your data, where the first column is "time" (in hrs) followed by data columns for each well/experiment. 

Start with some [examples](https://github.com/scott-saunders/labwork/blob/master/Growth_curve_fitting/data.zip).

Enjoy! [-Scott Saunders](https://scott-saunders.github.io/website/)


-------

### Upload your data

```{r}
fileInput("file1", "(.csv file)", multiple = FALSE, 
          accept = c("text/csv", "text/comma-separated-values,text/plain",".csv"))

df <- reactive({
  
  req(input$file1)
  
  df <- read_csv(input$file1$datapath) %>% 
    gather(key = 'well',value = 'absorbance',-time)
  
  return(df)
  
})

```

-------

### Download outputs

----

```{r}
 downloadHandler(
         filename = 'growth_curve_parameter_estimates.csv',
         outputArgs = list(label = 'Parameter estimates'),
         content = function(file) {
             write_csv(df_ests() %>% select(-c(data, fit_result, fit_errors, models, est_result, est_errors)), file)
         }
     )

```

--------

```{r}

pred_file <- reactive({  
  
  pred_file <- df_preds()

  if(input$biGomp){

    pred_file <- df_pred_ests()
    
    }
  
  })


downloadHandler(
  filename = 'growth_curve_model_fits.csv',
  outputArgs = list(label = 'Best fit curves'),
  content = function(file) { write_csv(pred_file() %>% select(-c(data, fit_result, fit_errors, models)), file)}
    )



```


# Select Data{ data-orientation=rows}

## Plots {data-height='300%' .tabset}

### Plot All


```{r}

output$overview_plot <- renderPlot({
  
  ggplot(df(), aes(time, absorbance, group = well)) + geom_path() + labs(title = 'Drag the box to select the data you would like to fit.')
  
})

plotOutput("overview_plot", brush = brushOpts(id = "overview_plot_brush"))

# Reactive that returns the whole dataset if there is no brush

selectedData <- reactive({
  data <- brushedPoints(df(), input$overview_plot_brush) 
  if (nrow(data) == 0)
    data <- df()
  data %>% filter(well %in% input$selected_wells)
})

```

### Plot Selected

```{r, results='asis'}

#output$select_plot <- 
  
  renderPlot({
  
  ggplot(selectedData(), aes(time, absorbance, group = well)) + geom_path()
  
})

#plotOutput("select_plot", height = '300px')

#renderUI(list(tags$hr(),plotOutput("overview_plot", brush = brushOpts(id = "overview_plot_brush"), height = '50px'), tags$hr(), plotOutput("select_plot", height = '100px')))

```

## Select Wells{data-height='100%'}

### Select Wells / Experiments

```{r}
renderUI(
  
  checkboxGroupInput(inputId = 'selected_wells', label = 'Choose your curves', choices = levels(factor(df()$well)), selected = levels(factor(df()$well)), width = '100%', inline = T)
  
)

```

## Tables {data-height='100%' .tabset}

### Table All


```{r}
renderTable({
  
  df() %>% pivot_wider(id_cols = 'time', names_from = 'well', values_from = 'absorbance' )
  
})
```

### Table Selected


```{r}
renderTable({
  selectedData() %>% pivot_wider(id_cols = 'time', names_from = 'well', values_from = 'absorbance' )
})
```


# Set Model Parameters{data-orientation=rows}

## Background 

### Background on Gompertz model parameters

[This paper](https://aem.asm.org/content/56/6/1875), it suggests that the modified Gompertz equation is an ideal way to parameterize a growth curve. They desribe the three parameters as follows: 

>The three phases of the growth curve can be described by three parameters: the maximum specific growth rate, $\mu_m$ is defined as the tangent in the inflection point; the lag time, $Lag$, is defined as the x-axis intercept of this tangent; and the asymptote $A$ is the maximal value reached.

The equation used here is the following:

$$ y = A*exp \left(-exp \left(\frac{\mu_m}{A}(Lag - t) + 1 \right)\right) + C$$

Where $C$ is a starting absorbance value. 

The models are actually fit with a nonlinear least squares method, specifically the [nls function](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/nls) from R. This method is extremely fast, but it requires pretty good guesses for parameter values. Therefore you can provide custom parameter values below. If many of your experiments cannot be fit, try playing with these starting parameters.

## Gompertz model parameters {.tabset}

### Single Gompertz

For a single growth phase. 

```{r}

numericInput("A", "Approximate the final absorbance value", 0.5)

numericInput("Lag", "Approximate the lag time", 4)

numericInput("Mu", "Approximate the growth rate", 0.2)

numericInput("C", "Approximate starting absorbance value", 0.05)

param_A <- reactive({
  #A <- 1

  if(!is.null(input$A)){ A <- input$A}

  A
})

param_Lag <- reactive({
  #Lag <- 1

  if(!is.null(input$Lag)){ Lag <- input$Lag}

  Lag
})

param_Mu <- reactive({
  #Mu <- 1

  if(!is.null(input$Mu)){ Mu <- input$Mu}

  Mu
})

param_C<- reactive({
  #C <- 1

  if(!is.null(input$C)){ C <- input$C}

  C
})

```

### Bi-Gompertz Model 

#### Do you want to fit two simultaneous growth phases?! 

***Warning:*** model fitting may be trickier. Good guesses for parameters are usually required. It is probably worth fitting with a single Gompertz first to find reasonable starting values. 

```{r}

checkboxInput('biGomp',label = 'Enable Bi - Gompertz', value = FALSE)

renderUI({  if(input$biGomp){numericInput("A_2", "Approximate the second A", 0.2)} })

renderUI({  if(input$biGomp){numericInput("Lag_2", "Approximate the second lag", 5)} })

renderUI({  if(input$biGomp){numericInput("Mu_2", "Approximate the second Mu", 0.3)} })

param_A_2 <- reactive({
  #A_2 <- 0.2

  if(!is.null(input$A_2)){ A_2 <- input$A_2}

  A_2
})

param_Lag_2 <- reactive({
  #Lag_2 <- 5

  if(!is.null(input$Lag_2)){ Lag_2 <- input$Lag_2}

  Lag_2
})

param_Mu_2 <- reactive({
  #Mu_2 <- 1

  if(!is.null(input$Mu_2)){ Mu_2 <- input$Mu_2}

  Mu_2
})
    
  


```

### Parameter Bounds

#### Single Model Parameters
```{r}

numericInput("A_low", "A_1 Lower bound", 0)
numericInput("A_up", "A_1 Upper bound", 100)

numericInput("Lag_low", "Lag_1 Lower bound", 0)
numericInput("Lag_up", "Lag_1 Upper bound", 100)

numericInput("Mu_low", "Mu_1 Lower bound", 0)
numericInput("Mu_up", "Mu_1 Upper bound", 10)

numericInput("C", "C Lower bound", -10)
numericInput("C", "C Upper bound", 10)


```

-----

#### Second Model Parameters

```{r}

renderUI({  if(input$biGomp){numericInput("A_2_low", "A_2 Lower Bound", 0)} })
renderUI({  if(input$biGomp){numericInput("A_2_up", "A_2 Upper Bound", 100)} })

renderUI({  if(input$biGomp){numericInput("Lag_2_low", "Lag_2 Lower Bound", 0)} })
renderUI({  if(input$biGomp){numericInput("Lag_2_up", "Lag_2 Upper Bound", 100)} })

renderUI({  if(input$biGomp){numericInput("Mu_2_low", "Mu_2 Lower Bound", 0)} })
renderUI({  if(input$biGomp){numericInput("Mu_2_up", "Mu_2 Upper Bound", 10)} })

```

### Model-free fit (Splines)

```{r}
# need to implement 3 choice drop down menu and restructure if statements to give another choice!

```

# Model Fits{data-orientation=rows}



```{r}
# This is where the models are actually fit

df_models <- reactive({
        
  
        # group and nest the data
        df_nest <- selectedData() %>%
            group_by(well) %>% 
            nest()
        
        
        # The nls function used to fit the data

        
        fit_gompertz_mod <- function(df){
            
            #A = 1; mu = 0.1; lam = 2
            
            mod <- nls(formula=absorbance~A*exp(-exp((Mu/A)*(Lag - time) + 1))+C, 
                       start = c(A = input$A, Mu = input$Mu, Lag = input$Lag, C = input$C), 
                       algorithm = 'port',
                       lower = c(A = input$A_low, Mu = input$Mu_low, Lag = input$Lag_low, C = input$C_low),
                       upper = c(A = input$A_up, Mu = input$Mu_up, Lag = input$Lag_up, C = input$C_up),
                       data = df)
            
            mod
        }
        
        
        if(input$biGomp == T){
          
          fit_gompertz_mod <- function(df){
            
            mod <- nls( formula=absorbance~( A_1*exp(-exp((Mu_1/A_1)*(Lag_1 - time) + 1)) ) + 
                                           ( A_2*exp(-exp((Mu_2/A_2)*(Lag_2 - time) + 1)) ) + C,
                        
#                        start = c(A_1 = 0.5, Mu_1 = 0.2, Lag_1 = 4, C= 0.05, 
#                                  A_2 = 0.2, Mu_2 = 0.3, Lag_2 = 5),
                        start = c(A_1 = input$A, Mu_1 = input$Mu, Lag_1 = input$Lag, C = input$C, 
                                  A_2 = input$A_2, Mu_2 = input$Mu_2, Lag_2 = input$Lag_2),
                        lower = c(A_1 = input$A_low, A_2 = input$A_2_low, Mu_1 = input$Mu_low, Mu_2 = input$Mu_2_low, Lag_1 = input$Lag_low, Lag_2 = input$Lag_2_low),
                        upper = c(A_1 = input$A_up, A_2 = input$A_2_up, Mu_1 = input$Mu_up, Mu_2 = input$Mu_2_up, Lag_1 = input$Lag_up, Lag_2 = input$Lag_2_up),
                        data = df, 
                        
                        algorithm = 'port')
            
            mod
          
          }
          
        }
          
        
        
        # fit data using the above function ...do this safely in case of errors
        df_models <- df_nest %>% 
            mutate(fit_result = map(data, safely(fit_gompertz_mod))) %>%
            ungroup() %>% 
            mutate(fit_errors = map(fit_result, 'error')) %>% 
            mutate(models = map(fit_result,'result')) %>% 
            mutate(fit_error_occured = map(.x = models, .f = is.null), fit_error_occured = unlist(fit_error_occured))
        
        #return(df_models)
        return(df_models)
        
    })
```

```{r}
    ##### generate the predictions from the models
    df_preds <- reactive({
        
        df_preds <- df_models() %>% 
            filter(fit_error_occured == FALSE) %>% 
            mutate(preds = map2(data, models, add_predictions)) %>% 
            unnest(preds)
            
        return(df_preds)
    })
```

```{r}

    ###### generate the parameter estimates from the models
    df_ests <- reactive({
        
        df_ests <- df_models() %>% 
            filter(fit_error_occured == FALSE) %>% 
            mutate(est_result = map(models, safely(tidy), conf.int = T)) %>% 
            mutate(est_errors = map(est_result, 'error')) %>% 
            mutate(ests = map(est_result,'result')) %>% 
            mutate(est_error_occured = map(.x = ests, .f = is.null), est_error_occured = unlist(est_error_occured)) %>% 
            mutate(ests = ifelse(est_error_occured == T, map(models, tidy, conf.int = F), ests)) %>% 
            unnest(ests)
        
        return(df_ests)
        
    })

```

```{r}
df_pred_ests <- reactive({

  df_pred_ests <- df_preds()

  if(input$biGomp){

    gen_gompertz <- function(a, mu, lag, c, time){

      a*exp(-exp((mu/a)*(lag - time) + 1 )) + c

      }

    df_pred_ests <- left_join(df_preds(),
                              df_ests() %>%
                                pivot_wider(id_cols = 'well',
                                            names_from = 'term',
                                            values_from = 'estimate' ),
                              by = 'well') %>%
      mutate(pred_1 = gen_gompertz(a = A_1, mu = Mu_1, lag = Lag_1, c = C, time = time)) %>%
      mutate(pred_2 = gen_gompertz(a = A_2, mu = Mu_2, lag = Lag_2, c = C, time = time))

  }

    return(df_pred_ests)
})

#renderDataTable(df_pred_ests() %>% select(well, fit_error_occured, A_2))

```



## Plot overviews{.tabset}

### Fit Plots
```{r}

plotOutput("plot")

output$plot <- renderPlot({
  
  p <- ggplot(data = df_preds(), aes_string(x=df_preds()$time, y = df_preds()$absorbance)) + 
    geom_point(shape = 21) + 
    geom_path(aes(y = df_preds()$pred), size = 1, color = 'blue')+ 
    facet_wrap(~well, scales = 'free') +
    labs(x = 'Time (Hrs)', y = 'Absorbance') + theme_bw()
  
  if(input$biGomp){

    p <- ggplot(df_pred_ests(), aes(x = df_pred_ests()$time)) +
      geom_point(aes(y = df_pred_ests()$absorbance), shape = 21)+
      geom_path(aes(y = df_pred_ests()$pred), color = 'blue', size = 1) +
      geom_path(aes(y = df_pred_ests()$pred_1), color = 'red', size = 1) +
      geom_path(aes(y = df_pred_ests()$pred_2), color = 'red', linetype = 2, size = 1) +
      facet_wrap(~well, scales = 'free')

  }
  
  print(p)
        
    })

```

### Error Plots

```{r}

renderPlot({
  
  df_errors <- df_models() %>% filter(fit_error_occured == T)
  
  df_error_plot <- left_join(df_errors, selectedData(), by = 'well')
  
  p <- ggplot(data = df_error_plot, aes_string(x=df_error_plot$time, y = df_error_plot$absorbance)) + 
    geom_point(shape = 21) + 
    facet_wrap(~well, scales = 'free') +
    labs(x = 'Time (Hrs)', y = 'Absorbance') + theme_bw()
  
  print(p)
})

```


## Table{data-height='75%'}

### Error Table

```{r}
renderTable({df_models() %>% select(well, fit_error_occured)})
```

# Parameter Estimates

### Plot estimates{data-height='100%'}
```{r}
renderPlot({
        
        p2 <- ggplot(data = df_ests(), aes(x=df_ests()$well, y = df_ests()$estimate)) + geom_point(color = 'red')+
            facet_wrap(~term, scales = 'free') +
            labs(x = 'Well', y = 'Parameter Estimate') + theme_bw()
        
        if(df_ests()$est_error_occured == F){
          p2 = p2 + geom_pointrange(aes(ymin = df_ests()$conf.low, ymax = df_ests()$conf.high )) 
        }
        
        print(p2)
        
    })

```

### Table estimates{data-height='25%'}

```{r}
renderTable({df_ests() %>% select(well, term, estimate, est_error_occured)})
```
